package com.transformplatform.api.persistence.repository

import com.transformplatform.api.persistence.entity.FileLogJpaEntity
import org.springframework.data.domain.Pageable
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Query
import org.springframework.data.repository.query.Param

interface JpaFileLogRepository : JpaRepository<FileLogJpaEntity, String> {

    // ── Primary access patterns ────────────────────────────────────────────────

    /** All files for a window, newest first. */
    fun findByWindowIdOrderByArrivedAtDesc(windowId: String): List<FileLogJpaEntity>

    /** Files for a profile, newest first with limit. */
    fun findByProfileIdOrderByArrivedAtDesc(profileId: String, pageable: Pageable): List<FileLogJpaEntity>

    /** Files by direction (INBOUND or OUTBOUND). */
    fun findByDirectionOrderByArrivedAtDesc(direction: String, pageable: Pageable): List<FileLogJpaEntity>

    /** All files generated by a specific execution. */
    fun findByGeneratedByExecutionId(executionId: String): List<FileLogJpaEntity>

    /** All files, newest first with limit. */
    @Query("SELECT f FROM FileLogJpaEntity f ORDER BY f.arrivedAt DESC")
    fun findAllPaged(pageable: Pageable): List<FileLogJpaEntity>

    // ── Idempotency check ─────────────────────────────────────────────────────

    /**
     * Check if an inbound file with the same (windowId, integrationId, remoteIdentifier)
     * already exists. Prevents duplicate ingestion.
     */
    @Query(
        """
        SELECT CASE WHEN COUNT(f) > 0 THEN TRUE ELSE FALSE END
        FROM FileLogJpaEntity f
        WHERE f.direction = 'INBOUND'
          AND f.windowId = :windowId
          AND f.integrationId = :integrationId
          AND f.remoteIdentifier = :remoteIdentifier
    """,
    )
    fun existsInbound(
        @Param("windowId") windowId: String,
        @Param("integrationId") integrationId: String,
        @Param("remoteIdentifier") remoteIdentifier: String,
    ): Boolean
}
