package com.transformplatform.scheduler.repository

import com.transformplatform.common.domain.filelog.FileDirection
import com.transformplatform.common.domain.filelog.FileLog

// ── FileLogRepository ─────────────────────────────────────────────────────────
//
// Persistence interface for the file_log table.
// Implemented by JpaFileLogRepositoryAdapter in platform-api.

interface FileLogRepository {

    // ── Write ─────────────────────────────────────────────────────────────────

    fun save(fileLog: FileLog): FileLog

    // ── Read ──────────────────────────────────────────────────────────────────

    fun findById(id: String): FileLog?

    /** All file log entries for a given window (inbound files). */
    fun findByWindowId(windowId: String): List<FileLog>

    /** All entries for a profile, newest first. */
    fun findByProfileId(profileId: String, limit: Int = 50): List<FileLog>

    /** All entries for a direction (INBOUND or OUTBOUND). */
    fun findByDirection(direction: FileDirection, limit: Int = 100): List<FileLog>

    /** Files generated by a specific execution (OUTBOUND). */
    fun findByGeneratedByExecutionId(executionId: String): List<FileLog>

    /** All entries, newest first. */
    fun findAll(limit: Int = 100): List<FileLog>

    // ── Idempotency check ─────────────────────────────────────────────────────

    /**
     * Returns true if an inbound file with the same integrationId + remoteIdentifier
     * has already been recorded for this window. Used to prevent duplicate ingestion.
     */
    fun existsInbound(windowId: String, integrationId: String, remoteIdentifier: String): Boolean
}
