package com.transformplatform.common.domain.filelog

import java.time.Instant
import java.util.UUID

// ── FileDirection ─────────────────────────────────────────────────────────────

enum class FileDirection {
    /** File received from an external source (e.g. SFTP download, API upload). */
    INBOUND,

    /** File produced by the platform (e.g. ACH file generated by GENERATE_FILE step). */
    OUTBOUND,
}

// ── FileLogStatus ─────────────────────────────────────────────────────────────

enum class FileLogStatus {
    /** File record created; processing not started. */
    RECEIVED,

    /** File is actively being processed. */
    PROCESSING,

    /** File was fully processed (parsed, validated, forwarded, etc.). */
    PROCESSED,

    /** Processing failed; see errorMessage. */
    FAILED,

    /** File was skipped (duplicate, filtered out). */
    SKIPPED,
}

// ── FileLog ───────────────────────────────────────────────────────────────────
//
// Ledger entry for every file that moves through the platform — both inbound
// (received from external systems via SFTP, API, etc.) and outbound (generated
// by GENERATE_FILE workflow steps).
//
// Inbound files are linked to the window that received them via `windowId`.
// Outbound files are linked to the execution that produced them via `generatedByExecutionId`.
//
// Idempotency: inbound files with the same (integrationId, remoteIdentifier) pair
// in the same window are detected and stored only once.

data class FileLog(

    val id: String = UUID.randomUUID().toString(),

    /** INBOUND = received; OUTBOUND = generated by the platform. */
    val direction: FileDirection,

    // ── Source / destination ──────────────────────────────────────────────────

    /** The ServiceIntegration that delivered or will receive this file. Nullable for API ingestion. */
    val integrationId: String? = null,

    /**
     * Source identifier within the integration:
     *   INBOUND  → remote path on SFTP server, S3 key, message ID, etc.
     *   OUTBOUND → target delivery path or queue name.
     */
    val remoteIdentifier: String? = null,

    /** Original filename as seen on the source system. */
    val fileName: String,

    // ── Window / execution linkage ────────────────────────────────────────────

    /** The window that received or initiated this file. */
    val windowId: String? = null,

    val profileId: String? = null,
    val clientId: String? = null,

    /** For OUTBOUND files: the execution that generated this file. */
    val generatedByExecutionId: String? = null,

    // ── File metadata ─────────────────────────────────────────────────────────

    val fileSizeBytes: Long? = null,

    /** SHA-256 of the file content. Used for deduplication and integrity. */
    val contentChecksum: String? = null,

    /** MIME type or format hint (e.g. "text/xml", "application/x-nacha"). */
    val mimeType: String? = null,

    // ── Processing status ─────────────────────────────────────────────────────

    val status: FileLogStatus = FileLogStatus.RECEIVED,

    val errorMessage: String? = null,

    // ── Timestamps ────────────────────────────────────────────────────────────

    /** When the file was first observed / received / created. */
    val arrivedAt: Instant = Instant.now(),

    /** When processing completed (PROCESSED or FAILED). */
    val processedAt: Instant? = null,
)
