package com.transformplatform.api.persistence.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.Instant

// ── FileLogJpaEntity ──────────────────────────────────────────────────────────
//
// JPA representation of the `file_log` table.
//
// Tracks every file that moves through the platform:
//   INBOUND  — received from external systems (SFTP, API upload, etc.)
//   OUTBOUND — generated by workflow steps (GENERATE_FILE, etc.)
//
// Idempotency index for inbound:
//   UNIQUE (integration_id, remote_identifier, window_id) WHERE direction = 'INBOUND'
//   Enforced at DB level; adapter catches DataIntegrityViolationException.
//
// FK relationships (string-only, no @ManyToOne):
//   window_id                  → windows(window_id)
//   generated_by_execution_id  → window_action_executions(execution_id)

@Entity
@Table(name = "file_log")
class FileLogJpaEntity {

    @Id
    @Column(name = "id", nullable = false, length = 255)
    var id: String = ""

    /** INBOUND or OUTBOUND */
    @Column(name = "direction", nullable = false, length = 20)
    var direction: String = "INBOUND"

    // ── Source / destination ──────────────────────────────────────────────────

    /** ServiceIntegration UUID. Nullable for API-ingested files. */
    @Column(name = "integration_id", length = 255)
    var integrationId: String? = null

    /** SFTP path, S3 key, queue name, or other integration-specific identifier. */
    @Column(name = "remote_identifier")
    var remoteIdentifier: String? = null

    @Column(name = "file_name", nullable = false)
    var fileName: String = ""

    // ── Linkage ───────────────────────────────────────────────────────────────

    @Column(name = "window_id", length = 255)
    var windowId: String? = null

    @Column(name = "profile_id", length = 255)
    var profileId: String? = null

    @Column(name = "client_id", length = 255)
    var clientId: String? = null

    /** For OUTBOUND files: FK to window_action_executions(execution_id). */
    @Column(name = "generated_by_execution_id", length = 255)
    var generatedByExecutionId: String? = null

    // ── File metadata ─────────────────────────────────────────────────────────

    @Column(name = "file_size_bytes")
    var fileSizeBytes: Long? = null

    @Column(name = "content_checksum", length = 64)
    var contentChecksum: String? = null

    @Column(name = "mime_type", length = 128)
    var mimeType: String? = null

    // ── Processing status ─────────────────────────────────────────────────────

    @Column(name = "status", nullable = false, length = 50)
    var status: String = "RECEIVED"

    @Column(name = "error_message")
    var errorMessage: String? = null

    // ── Timestamps ────────────────────────────────────────────────────────────

    @Column(name = "arrived_at", nullable = false)
    var arrivedAt: Instant = Instant.now()

    @Column(name = "processed_at")
    var processedAt: Instant? = null
}
