import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/transform-platform-api",
    },
    {
      type: "category",
      label: "Profiles",
      link: {
        type: "doc",
        id: "api/profiles",
      },
      items: [
        {
          type: "doc",
          id: "api/list-profiles",
          label: "List all Profiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-profile",
          label: "Create a Profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-profile",
          label: "Get a Profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-profile",
          label: "Update a Profile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-profile",
          label: "Delete a Profile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/enable-profile",
          label: "Enable a Profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-profile",
          label: "Disable a Profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/validate-profile",
          label: "Validate a Profile config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/rollback-profile",
          label: "Rollback to a previous version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-profile-history",
          label: "Get Profile revision history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/manual-trigger",
          label: "Manually trigger ON_MANUAL_TRIGGER actions",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Windows",
      link: {
        type: "doc",
        id: "api/windows",
      },
      items: [
        {
          type: "doc",
          id: "api/list-window-instances",
          label: "List window instances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-window-instance",
          label: "Get a window instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/force-close-window",
          label: "Force-close an open window",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reprocess-window",
          label: "Reprocess a closed window",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-window-events",
          label: "List events collected in a window",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Actions",
      link: {
        type: "doc",
        id: "api/actions",
      },
      items: [
        {
          type: "doc",
          id: "api/list-actions",
          label: "List actions for a Profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-action",
          label: "Add an action to a Profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-action",
          label: "Update an action",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-action",
          label: "Remove an action from a Profile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/enable-action",
          label: "Enable a disabled action",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-action",
          label: "Disable an action without removing it",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "FileSpecs",
      link: {
        type: "doc",
        id: "api/file-specs",
      },
      items: [
        {
          type: "doc",
          id: "api/list-specs",
          label: "List all FileSpecs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-spec",
          label: "Create a FileSpec",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-spec",
          label: "Get a FileSpec",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-spec",
          label: "Replace a FileSpec",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-spec",
          label: "Delete a FileSpec",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Transform",
      link: {
        type: "doc",
        id: "api/transform",
      },
      items: [
        {
          type: "doc",
          id: "api/transform-file",
          label: "File → Events (inbound pipeline)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/transform-events",
          label: "Events → File (outbound pipeline)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      link: {
        type: "doc",
        id: "api/integrations",
      },
      items: [
        {
          type: "doc",
          id: "api/list-integrations",
          label: "List integrations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-integration",
          label: "Register an integration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-integration",
          label: "Get an integration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-integration",
          label: "Update an integration",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-integration",
          label: "Delete an integration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/test-integration",
          label: "Test connectivity",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Credentials",
      link: {
        type: "doc",
        id: "api/credentials",
      },
      items: [
        {
          type: "doc",
          id: "api/store-credential",
          label: "Store a credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-credential",
          label: "Delete a credential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/rotate-credential",
          label: "Rotate a credential",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Health",
      link: {
        type: "doc",
        id: "api/health-tag",
      },
      items: [
        {
          type: "doc",
          id: "api/health",
          label: "Health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/readiness",
          label: "Readiness probe",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/liveness",
          label: "Liveness probe",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/profilestatus",
          label: "ProfileStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/profilesummary",
          label: "ProfileSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pageofprofilesummary",
          label: "PageOfProfileSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/windowfrequency",
          label: "WindowFrequency",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/windowconfigschema",
          label: "WindowConfigSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/actioncondition",
          label: "ActionCondition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/actiontype",
          label: "ActionType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/actionstatus",
          label: "ActionStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/actionrequest",
          label: "ActionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/action",
          label: "Action",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/actionresult",
          label: "ActionResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/profilerequest",
          label: "ProfileRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/profile",
          label: "Profile",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/profilerevision",
          label: "ProfileRevision",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/validationreport",
          label: "ValidationReport",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/windowstate",
          label: "WindowState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/windowinstance",
          label: "WindowInstance",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pageofwindowinstance",
          label: "PageOfWindowInstance",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/windowevent",
          label: "WindowEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pageofwindowevent",
          label: "PageOfWindowEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fileformat",
          label: "FileFormat",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldtype",
          label: "FieldType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/errorseverity",
          label: "ErrorSeverity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/integrationtype",
          label: "IntegrationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectionstatus",
          label: "ConnectionStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/credentialtype",
          label: "CredentialType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filespecsummary",
          label: "FileSpecSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pageoffilespecsummary",
          label: "PageOfFileSpecSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldspec",
          label: "FieldSpec",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldvalidation",
          label: "FieldValidation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/correctionrule",
          label: "CorrectionRule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/validationrule",
          label: "ValidationRule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pipelinedestination",
          label: "PipelineDestination",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldmapping",
          label: "FieldMapping",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/outboundconfig",
          label: "OutboundConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filespecrequest",
          label: "FileSpecRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filespec",
          label: "FileSpec",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/processingresult",
          label: "ProcessingResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/recorderror",
          label: "RecordError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/eventbatchrequest",
          label: "EventBatchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/integrationsummary",
          label: "IntegrationSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/integrationrequest",
          label: "IntegrationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/integration",
          label: "Integration",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectivitytestresult",
          label: "ConnectivityTestResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/credentialrequest",
          label: "CredentialRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/credentialresponse",
          label: "CredentialResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/healthresponse",
          label: "HealthResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/problemdetail",
          label: "ProblemDetail",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
