import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/core/transform-platform-api",
    },
    {
      type: "category",
      label: "Spec Management",
      link: { type: "doc", id: "api/spec-management/spec-management" },
      items: [
        { type: "doc", id: "api/spec-management/create-spec",    label: "Create a file spec",          className: "api-method post"   },
        { type: "doc", id: "api/spec-management/list-specs",     label: "List all specs",              className: "api-method get"    },
        { type: "doc", id: "api/spec-management/get-spec",       label: "Get spec by ID",              className: "api-method get"    },
        { type: "doc", id: "api/spec-management/update-spec",    label: "Update an existing spec",     className: "api-method put"    },
        { type: "doc", id: "api/spec-management/delete-spec",    label: "Delete a spec",               className: "api-method delete" },
        { type: "doc", id: "api/spec-management/validate-spec",  label: "Validate a spec definition",  className: "api-method post"   },
      ],
    },
    {
      type: "category",
      label: "Transform",
      link: { type: "doc", id: "api/transform/transform" },
      items: [
        { type: "doc", id: "api/transform/file-to-events",        label: "Transform file → Kafka events", className: "api-method post" },
        { type: "doc", id: "api/transform/schedule-transform",    label: "Schedule a transformation",     className: "api-method post" },
        { type: "doc", id: "api/transform/get-transform-status",  label: "Get transformation status",     className: "api-method get"  },
      ],
    },
    {
      type: "category",
      label: "Health",
      link: { type: "doc", id: "api/health/health" },
      items: [
        { type: "doc", id: "api/health/health-check",     label: "Application health",          className: "api-method get" },
        { type: "doc", id: "api/health/liveness-probe",   label: "Kubernetes liveness probe",   className: "api-method get" },
        { type: "doc", id: "api/health/readiness-probe",  label: "Kubernetes readiness probe",  className: "api-method get" },
      ],
    },
    {
      type: "category",
      label: "Observability",
      link: { type: "doc", id: "api/observability/observability" },
      items: [
        { type: "doc", id: "api/observability/list-metrics",         label: "List available metrics",       className: "api-method get" },
        { type: "doc", id: "api/observability/get-metric",           label: "Get metric value",             className: "api-method get" },
        { type: "doc", id: "api/observability/prometheus-metrics",   label: "Prometheus scrape endpoint",   className: "api-method get" },
      ],
    },
    {
      type: "category",
      label: "Profiles",
      link: { type: "doc", id: "api/profiles/profiles" },
      items: [
        { type: "doc", id: "api/profiles/list-profiles",       label: "List all Profiles",                        className: "api-method get"    },
        { type: "doc", id: "api/profiles/create-profile",      label: "Create a Profile",                         className: "api-method post"   },
        { type: "doc", id: "api/profiles/get-profile",         label: "Get a Profile",                            className: "api-method get"    },
        { type: "doc", id: "api/profiles/update-profile",      label: "Update a Profile",                         className: "api-method put"    },
        { type: "doc", id: "api/profiles/delete-profile",      label: "Delete a Profile",                         className: "api-method delete" },
        { type: "doc", id: "api/profiles/enable-profile",      label: "Enable a Profile",                         className: "api-method post"   },
        { type: "doc", id: "api/profiles/disable-profile",     label: "Disable a Profile",                        className: "api-method post"   },
        { type: "doc", id: "api/profiles/validate-profile",    label: "Validate a Profile config",                className: "api-method post"   },
        { type: "doc", id: "api/profiles/rollback-profile",    label: "Rollback to a previous version",           className: "api-method post"   },
        { type: "doc", id: "api/profiles/get-profile-history", label: "Get Profile revision history",             className: "api-method get"    },
        { type: "doc", id: "api/profiles/manual-trigger",      label: "Manually trigger ON_MANUAL_TRIGGER actions", className: "api-method post" },
      ],
    },
    {
      type: "category",
      label: "Windows",
      link: { type: "doc", id: "api/windows/windows" },
      items: [
        { type: "doc", id: "api/windows/list-window-instances",  label: "List window instances",              className: "api-method get"  },
        { type: "doc", id: "api/windows/get-window-instance",    label: "Get a window instance",              className: "api-method get"  },
        { type: "doc", id: "api/windows/force-close-window",     label: "Force-close an open window",         className: "api-method post" },
        { type: "doc", id: "api/windows/reprocess-window",       label: "Reprocess a closed window",          className: "api-method post" },
        { type: "doc", id: "api/windows/list-window-events",     label: "List events collected in a window",  className: "api-method get"  },
      ],
    },
    {
      type: "category",
      label: "Actions",
      link: { type: "doc", id: "api/actions/actions" },
      items: [
        { type: "doc", id: "api/actions/list-actions",    label: "List actions for a Profile",          className: "api-method get"    },
        { type: "doc", id: "api/actions/add-action",      label: "Add an action to a Profile",          className: "api-method post"   },
        { type: "doc", id: "api/actions/update-action",   label: "Update an action",                    className: "api-method put"    },
        { type: "doc", id: "api/actions/delete-action",   label: "Remove an action from a Profile",     className: "api-method delete" },
        { type: "doc", id: "api/actions/enable-action",   label: "Enable a disabled action",            className: "api-method post"   },
        { type: "doc", id: "api/actions/disable-action",  label: "Disable an action without removing it", className: "api-method post" },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      link: { type: "doc", id: "api/integrations/integrations" },
      items: [
        { type: "doc", id: "api/integrations/list-integrations",    label: "List integrations",       className: "api-method get"    },
        { type: "doc", id: "api/integrations/create-integration",   label: "Register an integration", className: "api-method post"   },
        { type: "doc", id: "api/integrations/get-integration",      label: "Get an integration",      className: "api-method get"    },
        { type: "doc", id: "api/integrations/update-integration",   label: "Update an integration",   className: "api-method put"    },
        { type: "doc", id: "api/integrations/delete-integration",   label: "Delete an integration",   className: "api-method delete" },
        { type: "doc", id: "api/integrations/test-integration",     label: "Test connectivity",       className: "api-method post"   },
      ],
    },
    {
      type: "category",
      label: "Credentials",
      link: { type: "doc", id: "api/credentials/credentials" },
      items: [
        { type: "doc", id: "api/credentials/store-credential",    label: "Store a credential",   className: "api-method post"   },
        { type: "doc", id: "api/credentials/delete-credential",   label: "Delete a credential",  className: "api-method delete" },
        { type: "doc", id: "api/credentials/rotate-credential",   label: "Rotate a credential",  className: "api-method put"    },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        // ── Coming Soon Schemas ────────────────────────────────────────────────
        { type: "doc", id: "api/core/schemas/profilestatus",            label: "ProfileStatus",            className: "schema" },
        { type: "doc", id: "api/core/schemas/windowtype",               label: "WindowType",               className: "schema" },
        { type: "doc", id: "api/core/schemas/actiontype",               label: "ActionType",               className: "schema" },
        { type: "doc", id: "api/core/schemas/actiontrigger",            label: "ActionTrigger",            className: "schema" },
        { type: "doc", id: "api/core/schemas/integrationtype",          label: "IntegrationType",          className: "schema" },
        { type: "doc", id: "api/core/schemas/credentialtype",           label: "CredentialType",           className: "schema" },
        { type: "doc", id: "api/core/schemas/createprofilerequest",     label: "CreateProfileRequest",     className: "schema" },
        { type: "doc", id: "api/core/schemas/profileresponse",          label: "ProfileResponse",          className: "schema" },
        { type: "doc", id: "api/core/schemas/createwindowrequest",      label: "CreateWindowRequest",      className: "schema" },
        { type: "doc", id: "api/core/schemas/windowresponse",           label: "WindowResponse",           className: "schema" },
        { type: "doc", id: "api/core/schemas/createactionrequest",      label: "CreateActionRequest",      className: "schema" },
        { type: "doc", id: "api/core/schemas/actionresponse",           label: "ActionResponse",           className: "schema" },
        { type: "doc", id: "api/core/schemas/createintegrationrequest", label: "CreateIntegrationRequest", className: "schema" },
        { type: "doc", id: "api/core/schemas/integrationresponse",      label: "IntegrationResponse",      className: "schema" },
        { type: "doc", id: "api/core/schemas/createcredentialrequest",  label: "CreateCredentialRequest",  className: "schema" },
        { type: "doc", id: "api/core/schemas/credentialresponse",       label: "CredentialResponse",       className: "schema" },
        // ── Core Schemas ──────────────────────────────────────────────────────
        { type: "doc", id: "api/core/schemas/fileformat",               label: "FileFormat",               className: "schema" },
        { type: "doc", id: "api/core/schemas/fieldtype",                label: "FieldType",                className: "schema" },
        { type: "doc", id: "api/core/schemas/severity",                 label: "Severity",                 className: "schema" },
        { type: "doc", id: "api/core/schemas/ruletype",                 label: "RuleType",                 className: "schema" },
        { type: "doc", id: "api/core/schemas/correctiontype",           label: "CorrectionType",           className: "schema" },
        { type: "doc", id: "api/core/schemas/sourcetype",               label: "SourceType",               className: "schema" },
        { type: "doc", id: "api/core/schemas/fieldspec",                label: "FieldSpec",                className: "schema" },
        { type: "doc", id: "api/core/schemas/validationrule",           label: "ValidationRule",           className: "schema" },
        { type: "doc", id: "api/core/schemas/correctionrule",           label: "CorrectionRule",           className: "schema" },
        { type: "doc", id: "api/core/schemas/fieldmapping",             label: "FieldMapping",             className: "schema" },
        { type: "doc", id: "api/core/schemas/outputspec",               label: "OutputSpec",               className: "schema" },
        { type: "doc", id: "api/core/schemas/createspecrequest",        label: "CreateSpecRequest",        className: "schema" },
        { type: "doc", id: "api/core/schemas/transformrequest",         label: "TransformRequest",         className: "schema" },
        { type: "doc", id: "api/core/schemas/specresponse",             label: "SpecResponse",             className: "schema" },
        { type: "doc", id: "api/core/schemas/transformresponse",        label: "TransformResponse",        className: "schema" },
        { type: "doc", id: "api/core/schemas/errordetail",              label: "ErrorDetail",              className: "schema" },
        { type: "doc", id: "api/core/schemas/validationreport",         label: "ValidationReport",         className: "schema" },
        { type: "doc", id: "api/core/schemas/errorresponse",            label: "ErrorResponse",            className: "schema" },
        { type: "doc", id: "api/core/schemas/healthresponse",           label: "HealthResponse",           className: "schema" },
        { type: "doc", id: "api/core/schemas/simplehealthresponse",     label: "SimpleHealthResponse",     className: "schema" },
      ],
    },
  ],
};

export default sidebar.apisidebar;
