package com.transformplatform.api.controller.filelog

import com.transformplatform.api.service.workflow.FileArrivalHandlerService
import com.transformplatform.common.domain.filelog.FileDirection
import com.transformplatform.common.domain.filelog.FileLog
import com.transformplatform.common.domain.window.WindowStatus
import com.transformplatform.scheduler.repository.FileLogRepository
import com.transformplatform.scheduler.repository.WindowInstanceRepository
import mu.KotlinLogging
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.multipart.MultipartFile

private val log = KotlinLogging.logger {}

// ── FileLogController ─────────────────────────────────────────────────────────
//
// REST endpoints for the file ledger.
//
// Read endpoints:
//   GET /api/files                           — list all (with optional direction filter)
//   GET /api/files/{id}                      — single entry
//   GET /api/windows/{windowId}/files        — files received by a window
//   GET /api/executions/{executionId}/files  — files generated by an execution
//   GET /api/profiles/{profileId}/files      — files for a profile
//
// Write endpoints:
//   POST /api/files/inbound                  — record an inbound file arrival (metadata only)
//   POST /api/windows/{windowId}/submit-file — upload + process a file into an OPEN window
//     (test / manual ingestion endpoint — triggers the full workflow pipeline)

@RestController
@RequestMapping("/api")
class FileLogController(
    private val fileLogRepo: FileLogRepository,
    private val windowRepo: WindowInstanceRepository,
    private val fileArrivalHandler: FileArrivalHandlerService,
) {

    // ── GET /api/files ─────────────────────────────────────────────────────────

    @GetMapping("/files")
    fun listFiles(
        @RequestParam(required = false) direction: String?,
        @RequestParam(required = false, defaultValue = "100") limit: Int,
    ): List<FileLogResponse> {
        val files = when {
            direction != null -> {
                val dir = try {
                    FileDirection.valueOf(direction.uppercase())
                } catch (ex: IllegalArgumentException) {
                    throw IllegalArgumentException("Invalid direction: $direction. Must be INBOUND or OUTBOUND")
                }
                fileLogRepo.findByDirection(dir, limit)
            }
            else -> fileLogRepo.findAll(limit)
        }
        log.debug { "listFiles: returning ${files.size} entries (direction=$direction)" }
        return files.map { it.toResponse() }
    }

    // ── GET /api/files/{id} ────────────────────────────────────────────────────

    @GetMapping("/files/{id}")
    fun getFile(@PathVariable id: String): ResponseEntity<FileLogResponse> {
        val file = fileLogRepo.findById(id) ?: return ResponseEntity.notFound().build()
        return ResponseEntity.ok(file.toResponse())
    }

    // ── GET /api/windows/{windowId}/files ──────────────────────────────────────

    @GetMapping("/windows/{windowId}/files")
    fun getWindowFiles(@PathVariable windowId: String): List<FileLogResponse> = fileLogRepo.findByWindowId(windowId).map { it.toResponse() }

    // ── GET /api/executions/{executionId}/files ────────────────────────────────

    @GetMapping("/executions/{executionId}/files")
    fun getExecutionFiles(@PathVariable executionId: String): List<FileLogResponse> =
        fileLogRepo.findByGeneratedByExecutionId(executionId).map { it.toResponse() }

    // ── GET /api/profiles/{profileId}/files ───────────────────────────────────

    @GetMapping("/profiles/{profileId}/files")
    fun getProfileFiles(
        @PathVariable profileId: String,
        @RequestParam(required = false, defaultValue = "50") limit: Int,
    ): List<FileLogResponse> = fileLogRepo.findByProfileId(profileId, limit).map { it.toResponse() }

    // ── POST /api/files/inbound ────────────────────────────────────────────────
    //
    // Called by the SFTP listener / file-arrival handler when a new file lands.
    // Records the file in the ledger and triggers the file arrival workflow.
    // The file content is expected to already be in MinIO (remoteIdentifier = MinIO key).
    // Returns 200 OK with the created entry, or 409 Conflict if already recorded.

    @PostMapping("/files/inbound")
    fun recordInboundFile(@RequestBody request: IngestFileRequest): ResponseEntity<FileLogResponse> {
        // Idempotency check (windowId + integrationId + remoteIdentifier)
        if (request.windowId != null && request.integrationId != null && request.remoteIdentifier != null) {
            if (fileLogRepo.existsInbound(request.windowId, request.integrationId, request.remoteIdentifier)) {
                log.warn {
                    "Duplicate inbound file ignored: window=${request.windowId} " +
                        "integration=${request.integrationId} path=${request.remoteIdentifier}"
                }
                return ResponseEntity.status(409).build()
            }
        }

        val fileLog = FileLog(
            direction = FileDirection.INBOUND,
            integrationId = request.integrationId,
            remoteIdentifier = request.remoteIdentifier,
            fileName = request.fileName,
            windowId = request.windowId,
            profileId = request.profileId,
            clientId = request.clientId,
            fileSizeBytes = request.fileSizeBytes,
            contentChecksum = request.contentChecksum,
            mimeType = request.mimeType,
        )

        val saved = fileLogRepo.save(fileLog)
        log.info { "Recorded inbound file: id=${saved.id} file=${saved.fileName} window=${saved.windowId}" }

        // Trigger the file arrival workflow (file is already in MinIO — no content stream needed)
        try {
            val result = fileArrivalHandler.onFileArrived(saved)
            log.info {
                "FileArrival result: matched=${result.matched}, window=${result.windowId}, " +
                    "records=${result.recordsProcessed}, msg=${result.message}"
            }
        } catch (ex: Exception) {
            log.error(ex) { "FileArrival handler error for file ${saved.id}: ${ex.message}" }
        }

        return ResponseEntity.ok(saved.toResponse())
    }

    // ── POST /api/windows/{windowId}/submit-file ───────────────────────────────
    //
    // Manual / test endpoint: upload a file directly into an OPEN window.
    //
    // This is the full end-to-end test path:
    //   1. Upload the file to MinIO
    //   2. Record in file ledger
    //   3. Add to window's arrivedFileHandles
    //   4. Evaluate FILE_ARRIVAL close trigger
    //   5. Run ON_FILE_ARRIVED action chain (PARSE → VALIDATE → NOTIFY to Kafka)
    //   6. Transition window to CLOSED
    //
    // In production the SFTP Camel route handles steps 1-2; this endpoint replicates
    // that for manual testing without needing a live SFTP server.

    @PostMapping(
        "/windows/{windowId}/submit-file",
        consumes = [MediaType.MULTIPART_FORM_DATA_VALUE],
    )
    fun submitFileToWindow(
        @PathVariable windowId: String,
        @RequestParam("file") file: MultipartFile,
        @RequestParam(required = false) integrationId: String?,
    ): ResponseEntity<Map<String, Any?>> {
        val window = windowRepo.findById(windowId)
            ?: throw NoSuchElementException("Window $windowId not found")

        if (window.status != WindowStatus.OPEN) {
            throw IllegalStateException(
                "Window $windowId is ${window.status} — must be OPEN to submit files",
            )
        }

        val effectiveIntegrationId = integrationId ?: "manual"
        val fileName = file.originalFilename ?: file.name

        // Idempotency: reject if this file was already submitted to this window
        if (fileLogRepo.existsInbound(windowId, effectiveIntegrationId, fileName)) {
            throw IllegalStateException(
                "File '$fileName' has already been submitted to window $windowId",
            )
        }

        // Create ledger entry first
        val fileLog = FileLog(
            direction = FileDirection.INBOUND,
            integrationId = effectiveIntegrationId,
            remoteIdentifier = null, // will be set to MinIO key by FileArrivalHandlerService
            fileName = fileName,
            windowId = windowId,
            profileId = window.profileId,
            fileSizeBytes = file.size,
            mimeType = file.contentType,
        )
        val saved = fileLogRepo.save(fileLog)

        log.info {
            "submitFileToWindow: processing '$fileName' " +
                "(size=${file.size}, windowId=$windowId, integrationId=$effectiveIntegrationId)"
        }

        // Delegate to the handler — this uploads to MinIO + runs the full workflow
        val result = fileArrivalHandler.onFileArrived(saved, file.inputStream)

        return ResponseEntity.ok(
            mapOf(
                "fileLogId" to saved.id,
                "windowId" to windowId,
                "fileName" to fileName,
                "matched" to result.matched,
                "recordsProcessed" to result.recordsProcessed,
                "message" to result.message,
            ),
        )
    }
}
